# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import tts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tts.models.upload_file)),
                ('text', models.CharField(default='', max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
